<script lang="ts" module>
	import { type VariantProps, tv } from 'tailwind-variants';
	import { cn, type WithElementRef } from '$lib/utils/stylingUtils.js';
	import type { HTMLAnchorAttributes, HTMLButtonAttributes } from 'svelte/elements';

	/*
	 * Generated by `shadcn-svelte add button`, then re-tabled against the OpenIdle
	 * design system's Button (Button.jsx): its variant and size vocabulary
	 * replaces shadcn's (`default|outline|link` and the `icon-*` sizes have no
	 * counterpart in the design and are gone). `shadcn-svelte update` would
	 * overwrite this file, so treat it as a local fork.
	 *
	 * Four spec details that look like mistakes but are not:
	 * - The default variant is `secondary`, not the generator's most prominent
	 *   one: the design leans on un-varianted buttons for its secondary look, so
	 *   a bare `<Button>` is the quiet one and prominence is always opted into.
	 * - `disabled:pointer-events-none` is deliberately absent, because it would
	 *   inherit the parent's cursor instead of showing `not-allowed`. Hover is
	 *   held back with `not-disabled:` on each variant instead.
	 * - Focus is an `outline`, not shadcn's `ring-*` box-shadow, because the
	 *   design calls for `outline-offset: 2px` and a shadow cannot be offset.
	 * - The press nudge is transitioned as `translate`, not `transform`:
	 *   `translate-y-px` compiles to the standalone `translate` property.
	 */
	export const buttonVariants = tv({
		base: 'group/button inline-flex shrink-0 cursor-pointer items-center justify-center gap-(--sp-3) border border-transparent bg-clip-padding whitespace-nowrap transition-[background-color,color,translate] duration-(--dur-fast) ease-out select-none focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring active:not-aria-[haspopup]:translate-y-px disabled:cursor-not-allowed disabled:opacity-42 [&_svg]:pointer-events-none [&_svg]:shrink-0',
		variants: {
			variant: {
				primary:
					'border-white/14 bg-action-primary text-action-primary-text shadow-[inset_0_1px_0_rgba(255,255,255,.25),var(--shadow-card)] not-disabled:hover:bg-action-primary-hover',
				secondary:
					'border-line-soft bg-surface-card text-text-body shadow-(--shadow-card) not-disabled:hover:bg-surface-card-hover not-disabled:hover:text-text-strong',
				ghost:
					'border-transparent bg-transparent text-text-muted shadow-none not-disabled:hover:bg-action-quiet not-disabled:hover:text-text-body',
				danger:
					'border-white/12 bg-(--crimson-600) text-text-strong shadow-[inset_0_1px_0_rgba(255,255,255,.18),var(--shadow-card)] not-disabled:hover:bg-(--crimson-500)'
			},
			// oi-label-* already carry the uppercase treatment and label tracking,
			// so never restate `uppercase`/`tracking-*`/`font-*` here.
			size: {
				sm: "oi-label-sm rounded-xs px-2.5 py-1.25 [&_svg:not([class*='size-'])]:size-3",
				md: "oi-label-md rounded-sm px-(--pad-control-x) py-(--pad-control-y) [&_svg:not([class*='size-'])]:size-3.5",
				lg: "oi-label-md rounded-sm px-(--sp-7) py-2.75 [&_svg:not([class*='size-'])]:size-4"
			}
		},
		defaultVariants: {
			variant: 'secondary',
			size: 'md'
		}
	});

	export type ButtonVariant = VariantProps<typeof buttonVariants>['variant'];
	export type ButtonSize = VariantProps<typeof buttonVariants>['size'];

	/*
	 * The one case where a `type` alias is required instead of `interface Props`:
	 * the component renders both <button> and <a>, so its props must intersect
	 * the two DOM element attribute sets, which an interface cannot extend.
	 */
	export type ButtonProps = WithElementRef<HTMLButtonAttributes> &
		WithElementRef<HTMLAnchorAttributes> & {
			variant?: ButtonVariant;
			size?: ButtonSize;
		};
</script>

<script lang="ts">
	// No defaults for `variant`/`size`: undefined falls through to tv's own
	// defaultVariants above, so the values live in exactly one place.
	let {
		class: className,
		variant,
		size,
		ref = $bindable(null),
		href = undefined,
		type = 'button',
		disabled,
		children,
		...restProps
	}: ButtonProps = $props();
</script>

{#if href}
	<a
		bind:this={ref}
		data-slot="button"
		class={cn(buttonVariants({ variant, size }), className)}
		href={disabled ? undefined : href}
		aria-disabled={disabled}
		role={disabled ? 'link' : undefined}
		tabindex={disabled ? -1 : undefined}
		{...restProps}
	>
		{@render children?.()}
	</a>
{:else}
	<button
		bind:this={ref}
		data-slot="button"
		class={cn(buttonVariants({ variant, size }), className)}
		{type}
		{disabled}
		{...restProps}
	>
		{@render children?.()}
	</button>
{/if}
