<script lang="ts">
	import { Dialog as DialogPrimitive } from 'bits-ui';
	import XIcon from '@lucide/svelte/icons/x';
	import { Button } from '$lib/components/ui/button/index.js';
	import { cn, type WithoutChildrenOrChild } from '$lib/utils/stylingUtils.js';
	// Siblings imported directly. The generator reaches the overlay through
	// ./index.js, which imports this file back — a cycle ESM tolerates but that
	// buys nothing.
	import DialogOverlay from './dialog-overlay.svelte';
	import DialogPortal from './dialog-portal.svelte';
	import type { ComponentProps, Snippet } from 'svelte';

	/*
	 * Generated by `shadcn-svelte add dialog`, then re-tabled against the OpenIdle
	 * design system. `shadcn-svelte update` would overwrite this file, so treat it
	 * as a local fork.
	 *
	 * The panel takes the design's lifted-surface vocabulary — `--shadow-pop`, the
	 * deepest shadow in the set and until now unused, over `surface-panel` — in
	 * place of shadcn's `bg-popover` and hairline `ring`.
	 *
	 * The close button is `size="sm"` with square padding rather than the
	 * generator's `size="icon-sm"`: the design has no icon-only size, so Button's
	 * fork dropped that whole size family.
	 *
	 * The enter/exit classes are tw-animate-css, which layout.css already imports
	 * and which costs no JavaScript. They are retimed to `--dur-base`; the
	 * design's `--ease-snap` is deliberately not used, since motion.css reserves
	 * its overshoot for the collect and level-up pop.
	 *
	 * They must be spelled `data-[state=open]`/`data-[state=closed]`: bits-ui
	 * reports the phase as `data-state`, and the shorter `data-open:` form
	 * Tailwind happily compiles targets a `[data-open]` attribute nothing sets,
	 * so the panel would appear with no transition at all.
	 */
	let {
		ref = $bindable(null),
		class: className,
		portalProps,
		children,
		showCloseButton = true,
		...restProps
	}: WithoutChildrenOrChild<DialogPrimitive.ContentProps> & {
		portalProps?: WithoutChildrenOrChild<ComponentProps<typeof DialogPortal>>;
		children: Snippet;
		showCloseButton?: boolean;
	} = $props();
</script>

<DialogPortal {...portalProps}>
	<DialogOverlay />
	<DialogPrimitive.Content
		bind:ref
		data-slot="dialog-content"
		class={cn(
			'fixed top-1/2 left-1/2 z-50 grid w-full max-w-[calc(100%-2rem)] -translate-x-1/2 -translate-y-1/2 gap-(--sp-6) rounded-lg border border-line-soft bg-surface-panel p-(--gutter-panel) text-text-body shadow-(--shadow-pop) duration-(--dur-base) ease-out outline-none data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=closed]:zoom-out-95 data-[state=open]:animate-in data-[state=open]:fade-in-0 data-[state=open]:zoom-in-95 sm:max-w-md',
			className
		)}
		{...restProps}
	>
		{@render children?.()}
		{#if showCloseButton}
			<DialogPrimitive.Close data-slot="dialog-close">
				{#snippet child({ props })}
					<Button
						variant="ghost"
						size="sm"
						class="absolute top-(--sp-5) right-(--sp-5) p-1.5"
						{...props}
					>
						<XIcon />
						<span class="sr-only">Close</span>
					</Button>
				{/snippet}
			</DialogPrimitive.Close>
		{/if}
	</DialogPrimitive.Content>
</DialogPortal>
