<script lang="ts">
	import { Dialog as DialogPrimitive } from 'bits-ui';
	import { cn } from '$lib/utils/stylingUtils.js';

	/*
	 * Generated by `shadcn-svelte add dialog`, then re-tabled against the OpenIdle
	 * design system. `shadcn-svelte update` would overwrite this file, so treat it
	 * as a local fork.
	 *
	 * The scrim is `--surface-overlay`, which the design system defined and
	 * nothing had spent until now.
	 *
	 * The generator's `backdrop-blur-xs` is dropped rather than swapped for the
	 * design's `--blur-overlay`. That token is a complete filter value rather than
	 * a radius, so reaching it takes `backdrop-filter-(--blur-overlay)` and not
	 * `backdrop-blur-(--blur-overlay)` — available, but a compositing layer over
	 * the whole viewport is a real cost, and a confirmation step does not need the
	 * decoration. Spend it when a surface exists that wants to read through.
	 *
	 * `z-50` is the generator's, and it is the first stacking value anywhere in
	 * the app. Author a `--z-*` family upstream before a second overlay — a toast,
	 * a tooltip, a dropdown — has to sit in a defined order with it.
	 */
	let {
		ref = $bindable(null),
		class: className,
		...restProps
	}: DialogPrimitive.OverlayProps = $props();
</script>

<DialogPrimitive.Overlay
	bind:ref
	data-slot="dialog-overlay"
	class={cn(
		'fixed inset-0 isolate z-50 bg-surface-overlay duration-(--dur-base) ease-out data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:animate-in data-[state=open]:fade-in-0',
		className
	)}
	{...restProps}
/>
