using System;
using System.Collections.Generic;
using System.IO;

namespace Generator.Core;

public sealed class CsEmitter : IDtoEmitter
{
    private readonly ScopedTextWriter _textWriter;
    private readonly List<string> _typeNames = new();
    
    public CsEmitter(TextWriter writer)
    {
        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("using System;");
        writer.WriteLine("using System.Text.Json.Serialization;");
        writer.WriteLine();
        writer.WriteLine($"namespace Backend.Dtos;");
        writer.WriteLine();
        
        _textWriter = new ScopedTextWriter(writer);
    }
    
    public void EmitDtos(DtoModel model)
    {
        foreach (Object obj in model.Objects)
        {
            EmitClass(obj);
        }
    }
    
    private void EmitClass(Object obj)
    {
        _typeNames.Add(obj.Name.UpperCamelCase);
        using (Scope _ = _textWriter.Scope($"public sealed class {obj.Name.UpperCamelCase} : {BaseType(obj)}"))
        {
            foreach (Property property in obj.Properties)
            {
                Property(property);
            }
        }
        _textWriter.WriteLine();
    }

    private void Property(Property property, string setter = "init")
    {
        _textWriter.WriteLine($"[JsonPropertyName(\"{property.Name.LowerCamelCase}\")]");
        _textWriter.WriteLine($"public {GetPropertyType(property)} {property.Name.UpperCamelCase} {{ get; {setter}; }}");
    }

    private string BaseType(Object obj)
    {
        return obj switch
        {
            Dto dto => "DtoBase",
            Event @event => "EventBase",
            Request request => "RequestBase",
            Response response => "ResponseBase",
            _ => throw new ArgumentOutOfRangeException(nameof(obj))
        };
    }

    private string GetPropertyType(Property property)
    {
        string str = property.PropertyType switch
        {
            PropertyType.Custom => property.PropertyTypeString.UpperCamelCase + "Dto",
            PropertyType.String => "string",
            PropertyType.Int => "int",
            PropertyType.Float => "float",
            PropertyType.Guid => "Guid",
            _ => throw new ArgumentOutOfRangeException()
        };
        return property.Multiple ? str + "[]" : str;
    }

    public void Dispose()
    {
        _textWriter.WriteLine("[JsonPolymorphic]");
        foreach (string typeName in _typeNames)
        {
            _textWriter.WriteLine($"[JsonDerivedType(typeof({typeName}), nameof({typeName}))]");
        }
        using (Scope _ = _textWriter.Scope($"public abstract class DtoBase"))
        { }
        _textWriter.WriteLine();
        using (Scope _ = _textWriter.Scope($"public abstract class RequestBase: DtoBase"))
        {
            Property(new Property(PropertyType.String, "string",  "RequestId", false), "set");
        }
        _textWriter.WriteLine();
        using (Scope _ = _textWriter.Scope($"public abstract class ResponseBase: DtoBase"))
        {
            Property(new Property(PropertyType.String, "string",  "RequestId", false), "set");
        }
        _textWriter.WriteLine();
        using (Scope _ = _textWriter.Scope($"public abstract class EventBase: DtoBase"))
        {
            Property(new Property(PropertyType.String, "string",  "EventId", false), "set");
        }
        _textWriter.WriteLine();
    }
}