using System;
using System.Collections.Generic;
using System.IO;

namespace Generator.Core;

public sealed class CsEmitter : IDtoEmitter
{
    private readonly ScopedTextWriter _textWriter;
    private readonly List<Object> _allObjects = new();

    public CsEmitter(TextWriter writer)
    {
        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("#nullable enable");
        writer.WriteLine("using System;");
        writer.WriteLine("using System.Text.Json.Serialization;");
        writer.WriteLine();
        writer.WriteLine("namespace Backend.Dtos;");
        writer.WriteLine();

        _textWriter = new ScopedTextWriter(writer);
    }

    public void EmitDtos(DtoModel model)
    {
        foreach (Object obj in model.AllObjects)
        {
            EmitClass(obj);
            _allObjects.Add(obj);
        }

        using (Scope _ = _textWriter.Scope("public enum ItemId"))
        {
            foreach (var item in model.Items.Values)
            {
                _textWriter.WriteLine($"{item.Name.UpperCamelCase},");
            }
        }

        using (Scope _ = _textWriter.Scope("public enum SkillId"))
        {
            foreach (Skill skill in model.Skills.Values)
            {
                _textWriter.WriteLine($"{skill.Name.UpperCamelCase},");
            }
        }
    }

    private void EmitClass(Object obj)
    {
        using (Scope _ = _textWriter.Scope($"public sealed class {obj.Name.UpperCamelCase} : {BaseType(obj)}"))
        {
            foreach (Property property in obj.Properties)
            {
                Property(property);
            }
        }
        _textWriter.WriteLine();
    }

    private void Property(Property property, string setter = "init")
    {
        _textWriter.WriteLine($"[JsonPropertyName(\"{property.Name.LowerCamelCase}\")]");
        _textWriter.WriteLine($"{GetPropertyModifiers(property)} {GetPropertyType(property)} {property.Name.UpperCamelCase} {{ get; {setter}; }}");
    }

    private string GetPropertyModifiers(Property property)
    {
        string str = "public";
        if (!property.Optional)
        {
            str += " required";
        }

        return str;
    }

    private string BaseType(Object obj)
    {
        return obj switch
        {
            Dto => "DtoBase",
            Event => "EventBase",
            Request => "RequestBase",
            Response => "ResponseBase",
            _ => throw new ArgumentOutOfRangeException(nameof(obj))
        };
    }

    private bool IsRequiredReferenceType(Property property)
    {
        // Optional properties should not be required
        if (property.Optional)
            return false;

        // Arrays are reference types and need required modifier
        if (property.Multiple)
            return true;

        // Check if the base type is a reference type
        return property.PropertyType switch
        {
            PropertyType.String => true,
            PropertyType.Custom => true,
            PropertyType.Int => false,
            PropertyType.Float => false,
            PropertyType.Guid => false,
            PropertyType.UserId => false,
            PropertyType.ProfileId => false,
            PropertyType.ItemId => false,
            PropertyType.SkillId => false,
            _ => false
        };
    }

    private string GetPropertyType(Property property)
    {
        string str = property.PropertyType switch
        {
            PropertyType.Custom => property.PropertyTypeString.UpperCamelCase + "Dto",
            PropertyType.String => "string",
            PropertyType.Int => "int",
            PropertyType.Float => "float",
            PropertyType.Guid => "Guid",
            PropertyType.UserId => "Guid",
            PropertyType.ProfileId => "Guid",
            PropertyType.ItemId => "ItemId",
            PropertyType.SkillId => "SkillId",
            _ => throw new ArgumentOutOfRangeException()
        };
        if (property.Multiple)
            str += "[]";
        if (property.Optional)
            str += "?";
        return str;
    }

    public void Dispose()
    {
        _textWriter.WriteLine("[JsonPolymorphic]");
        foreach (Object obj in _allObjects)
        {
            _textWriter.WriteLine($"[JsonDerivedType(typeof({obj.Name.UpperCamelCase}), nameof({obj.Name.UpperCamelCase}))]");
        }
        using (Scope _ = _textWriter.Scope("public abstract class DtoBase"))
        {
        }
        _textWriter.WriteLine();
        using (Scope _ = _textWriter.Scope("public abstract class RequestBase : DtoBase"))
        {
            Property(new Property(PropertyType.Int, "int", "RequestId", false, true), "set");
        }
        _textWriter.WriteLine();
        using (Scope _ = _textWriter.Scope("public abstract class ResponseBase : DtoBase"))
        {
            Property(new Property(PropertyType.Int, "int", "RequestId", false, true), "set");
        }
        _textWriter.WriteLine();
        using (Scope _ = _textWriter.Scope("public abstract class EventBase : DtoBase"))
        {
            Property(new Property(PropertyType.Int, "int", "EventId", false, true), "set");
        }
        _textWriter.WriteLine();
    }
}