using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;

namespace Generator.Core;

public sealed class CsEmitter : IDtoEmitter
{
    private readonly ScopedTextWriter _textWriter;
    private readonly List<Object> _allObjects = new();

    public CsEmitter(TextWriter writer)
    {
        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("#nullable enable");
        writer.WriteLine("using System;");
        writer.WriteLine("using System.Text.Json.Serialization;");
        writer.WriteLine("using Backend.Services;");
        writer.WriteLine();
        writer.WriteLine("namespace Backend.Dtos;");
        writer.WriteLine();

        _textWriter = new ScopedTextWriter(writer);
    }

    public void EmitDtos(DtoModel model)
    {
        foreach (Object obj in model.AllObjects)
        {
            EmitClass(obj);
            _allObjects.Add(obj);
        }

        EmitEnums(model);

        EmitDropTableData(model);
    }

    private void EmitEnums(DtoModel model)
    {
        foreach (Enum en in model.Enums.Values)
        {
            using (Scope _ = _textWriter.Scope($"public enum {en.Name.UpperCamelCase}"))
            {
                foreach (EnumValue item in en.GetEnums())
                {
                    _textWriter.WriteLine($"{item.Name.UpperCamelCase},");
                }
            }
        }
    }

    private void EmitDropTableData(DtoModel model)
    {
        _textWriter.WriteLine();
        using (Scope _ = _textWriter.Scope("public static class DropTableData"))
        {
            using (Scope __ = _textWriter.Scope("public static void AddAll(DropTableService service)"))
            {
                foreach (DropTable dropTable in model.DropTables.Values)
                {
                    EmitDropTable(dropTable);
                }
            }
        }
    }

    private void EmitDropTable(DropTable dropTable)
    {
        _textWriter.Write($"service.AddDropTable(DropTableId.{dropTable.Name.UpperCamelCase}, new DropTable(");
        if (dropTable.Drops.Count > 0)
        {
            _textWriter.WriteLine();
            using (Scope ___ = new(ScopeStyle.Indentation, _textWriter))
            {
                for (int i = 0; i < dropTable.Drops.Count; i++)
                {
                    string separator = i < dropTable.Drops.Count - 1 ? "," : "";
                    _textWriter.WriteLine($"{DropExpression(dropTable.Drops[i])}{separator}");
                }
            }
        }
        _textWriter.WriteLine("));");
    }

    private static string DropExpression(Drop drop)
    {
        if (drop.Item is not null)
        {
            return $"new ItemDrop({drop.Count}, {WeightLiteral(drop.Weight)}, ItemId.{new Casing(drop.Item).UpperCamelCase})";
        }

        if (drop.Table is not null)
        {
            
            return $"new TableDrop({drop.Count}, {WeightLiteral(drop.Weight)}, DropTableId.{new Casing(drop.Table!).UpperCamelCase})";
        }

        throw new NotSupportedException("Drop expressions should either drop a table or an item.");
    }

    private static string WeightLiteral(float weight)
    {
        return weight.ToString(CultureInfo.InvariantCulture) + "f";
    }

    private void EmitClass(Object obj)
    {
        using (Scope _ = _textWriter.Scope($"public sealed class {obj.Name.UpperCamelCase} : {BaseType(obj)}"))
        {
            foreach (Property property in obj.Properties)
            {
                Property(property);
            }
        }
        _textWriter.WriteLine();
    }

    private void Property(Property property, string setter = "init")
    {
        _textWriter.WriteLine($"[JsonPropertyName(\"{property.Name.LowerCamelCase}\")]");
        _textWriter.WriteLine($"{GetPropertyModifiers(property)} {GetPropertyType(property)} {property.Name.UpperCamelCase} {{ get; {setter}; }}");
    }

    private string GetPropertyModifiers(Property property)
    {
        string str = "public";
        if (!property.Optional)
        {
            str += " required";
        }

        return str;
    }

    private string BaseType(Object obj)
    {
        return obj switch
        {
            Dto => "DtoBase",
            Event => "EventBase",
            Request => "RequestBase",
            Response => "ResponseBase",
            _ => throw new ArgumentOutOfRangeException(nameof(obj))
        };
    }

    private string GetPropertyType(Property property)
    {
        if (property is CustomProperty custom)
        {
            string str = custom.Type.Name.UpperCamelCase;
            if (custom.Multiple)
                str += "[]";
            if (custom.Optional)
                str += "?";
            return str;
        }

        string builtIn = property.PropertyType switch
        {
            PropertyType.String => "string",
            PropertyType.Int => "int",
            PropertyType.Float => "float",
            PropertyType.Guid => "Guid",
            PropertyType.UserId => "Guid",
            PropertyType.ProfileId => "Guid",
            _ => throw new ArgumentOutOfRangeException()
        };
        if (property.Multiple)
            builtIn += "[]";
        if (property.Optional)
            builtIn += "?";
        return builtIn;
    }

    public void Dispose()
    {
        _textWriter.WriteLine("[JsonPolymorphic]");
        foreach (Object obj in _allObjects)
        {
            _textWriter.WriteLine($"[JsonDerivedType(typeof({obj.Name.UpperCamelCase}), nameof({obj.Name.UpperCamelCase}))]");
        }
        using (Scope _ = _textWriter.Scope("public abstract class DtoBase"))
        {
        }
        _textWriter.WriteLine();
        using (Scope _ = _textWriter.Scope("public abstract class RequestBase : DtoBase"))
        {
            Property(new Property(PropertyType.Int, "int", "RequestId", false, true), "set");
        }
        _textWriter.WriteLine();
        using (Scope _ = _textWriter.Scope("public abstract class ResponseBase : DtoBase"))
        {
            Property(new Property(PropertyType.Int, "int", "RequestId", false, true), "set");
        }
        _textWriter.WriteLine();
        using (Scope _ = _textWriter.Scope("public abstract class EventBase : DtoBase"))
        {
            Property(new Property(PropertyType.Int, "int", "EventId", false, true), "set");
        }
        _textWriter.WriteLine();
    }
}