using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;

namespace Generator.Core;

/// <summary>
/// Emits the protocol module the frontend imports. The output is committed and
/// has to pass `prettier --check` under Frontend/prettier.config.js untouched,
/// so this emitter reproduces prettier's own wrapping decisions rather than
/// merely printing valid TypeScript — see <see cref="Fits"/>,
/// <see cref="WriteUnion"/> and <see cref="WriteArray"/>.
/// </summary>
public sealed class TsEmitter : IDtoEmitter
{
    private const int PrintWidth = 100;

    /// <summary>
    /// Prettier measures a tab as tabWidth columns; prettier.config.js sets
    /// useTabs without setting tabWidth, so its default of 2 applies.
    /// </summary>
    private const int TabWidth = 2;

    private const string ItemIdEnumName = "ItemId";
    private const string SkillIdEnumName = "SkillId";
    private const string DropTableIdEnumName = "DropTableId";

    private readonly ScopedTextWriter _textWriter;
    private bool _firstBlock = true;

    public TsEmitter(TextWriter writer)
    {
        // Prettier's endOfLine default is 'lf'. The CLI's StreamWriter would
        // otherwise use Environment.NewLine, failing --check on every line of a
        // file generated on Windows. Scoped here so the C# output is untouched.
        writer.NewLine = "\n";
        _textWriter = new ScopedTextWriter(writer)
        {
            IndentUnit = "\t",
            BraceStyle = BraceStyle.SameLine,
        };

        _textWriter.WriteLine("// <auto-generated>");
        _textWriter.WriteLine("//     Generated from types.xml by Generators/Core/TsEmitter.cs.");
        _textWriter.WriteLine("//     Run `bun run gen:dto` to regenerate; edits are lost on the next run.");
        _textWriter.WriteLine("// </auto-generated>");
        _textWriter.WriteLine();

        EmitBases();
    }

    public void EmitDtos(DtoModel model)
    {
        EmitEnums(model);

        foreach (Object obj in model.AllObjects)
        {
            EmitInterface(obj);
        }

        EmitResponseUnion(model);
        EmitRequestMap(model);
        EmitEventMap(model);
        EmitGameData(model);
    }

    public void Dispose()
    {
        // Nothing to close: unlike the C# output there is no registry to write
        // once every type is known, so the whole module is emitted above.
    }

    /// <summary>
    /// Writes the single blank line prettier keeps between top-level
    /// declarations, without leaving one at the top or bottom of the file.
    /// </summary>
    private void Separate()
    {
        if (_firstBlock)
        {
            _firstBlock = false;
            return;
        }

        _textWriter.WriteLine();
    }

    private void EmitBases()
    {
        Separate();
        using (Scope _ = _textWriter.Scope("export interface DtoBase"))
        {
            _textWriter.WriteLine("$type: string;");
        }

        // requestId and eventId are optional because the backend genuinely omits
        // them: both are `int?` on the C# bases and SocketJsonSerializer sets
        // DefaultIgnoreCondition = WhenWritingDefault, so an unset id is absent
        // from the frame rather than sent as 0. classifyMessage depends on it.
        foreach (string name in new[] { "RequestBase", "ResponseBase" })
        {
            Separate();
            using (Scope _ = _textWriter.Scope($"export interface {name} extends DtoBase"))
            {
                _textWriter.WriteLine("requestId?: number;");
            }
        }

        // Timestamp is `long?` on the C# base and Socket.SendEventAsync stamps it
        // with epoch milliseconds on the way out, so it is optional here for the
        // same reason the ids are: WhenWritingDefault omits an unset one.
        Separate();
        using (Scope _ = _textWriter.Scope("export interface EventBase extends DtoBase"))
        {
            _textWriter.WriteLine("eventId?: number;");
            _textWriter.WriteLine("timestamp?: number;");
        }
    }

    private void EmitEnums(DtoModel model)
    {
        foreach (Enum en in model.Enums.Values)
        {
            Separate();
            WriteUnion($"export type {en.Name.UpperCamelCase}",
                en.GetEnums().Select(value => Quote(value.Name.UpperCamelCase)).ToList());
        }
    }

    private void EmitInterface(Object obj)
    {
        Separate();
        string name = obj.Name.UpperCamelCase;

        if (obj is Dto)
        {
            // A DTO is never the top-level frame: it is serialized under its own
            // declared type, and [JsonPolymorphic] sits only on DtoBase and is
            // not inherited. So a ProfileDto nested in a ListProfilesResponse
            // carries no $type, and must not extend DtoBase either.
            if (obj.Properties.Count == 0)
            {
                _textWriter.WriteLine($"export type {name} = Record<string, never>;");
                return;
            }

            using (Scope _ = _textWriter.Scope($"export interface {name}"))
            {
                foreach (Property property in obj.Properties)
                {
                    WriteProperty(property);
                }
            }
            return;
        }

        using (Scope _ = _textWriter.Scope($"export interface {name} extends {BaseType(obj)}"))
        {
            // Narrowing the inherited `$type: string` to a literal is what makes
            // ServerResponse a discriminated union the frontend can switch on.
            _textWriter.WriteLine($"$type: {Quote(name)};");
            foreach (Property property in obj.Properties)
            {
                WriteProperty(property);
            }
        }
    }

    /// <summary>
    /// The responses a request can be answered with, taken from the requests
    /// rather than from every declared response. That excludes a standalone
    /// &lt;Response&gt; such as ErrorResponse, which the client handles on its
    /// own branch, and keeps the union and RESPONSE_TYPES in sync by
    /// construction.
    /// </summary>
    private void EmitResponseUnion(DtoModel model)
    {
        List<string> names = model.Requests.Values
            .Select(request => request.Response.Name.UpperCamelCase)
            .ToList();

        Separate();
        WriteUnion("export type ServerResponse", names);

        Separate();
        WriteArray("export const RESPONSE_TYPES: ReadonlySet<string> = new Set(",
            names.Select(Quote).ToList(), ");", elementsAreObjects: false);
    }

    private void EmitRequestMap(DtoModel model)
    {
        Separate();
        if (model.Requests.Count == 0)
        {
            _textWriter.WriteLine("export type RequestMap = Record<string, never>;");
        }
        else
        {
            using (Scope _ = _textWriter.Scope("export type RequestMap =", ScopeStyle.Curly, ";"))
            {
                foreach (Request request in model.Requests.Values)
                {
                    WriteRequestEntry(request);
                }
            }
        }

        Separate();
        _textWriter.WriteLine("export type RequestType = keyof RequestMap;");
    }

    private void WriteRequestEntry(Request request)
    {
        string name = request.Name.UpperCamelCase;
        string response = request.Response.Name.UpperCamelCase;
        string payload = ObjectType(request.Properties);

        string flat = $"{name}: {{ payload: {payload}; response: {response} }};";
        if (Fits(flat))
        {
            _textWriter.WriteLine(flat);
            return;
        }

        using (Scope _ = _textWriter.Scope($"{name}:", ScopeStyle.Curly, ";"))
        {
            if (Fits($"payload: {payload};"))
            {
                _textWriter.WriteLine($"payload: {payload};");
            }
            else
            {
                using (Scope __ = _textWriter.Scope("payload:", ScopeStyle.Curly, ";"))
                {
                    foreach (Property property in request.Properties)
                    {
                        WriteProperty(property);
                    }
                }
            }
            _textWriter.WriteLine($"response: {response};");
        }
    }

    private void EmitEventMap(DtoModel model)
    {
        Separate();
        if (model.Events.Count == 0)
        {
            _textWriter.WriteLine("export type EventMap = Record<string, never>;");
        }
        else
        {
            using (Scope _ = _textWriter.Scope("export type EventMap =", ScopeStyle.Curly, ";"))
            {
                foreach (Event ev in model.Events.Values)
                {
                    WriteEventEntry(ev);
                }
            }
        }

        Separate();
        _textWriter.WriteLine("export type EventType = keyof EventMap;");

        Separate();
        _textWriter.WriteLine(
            "export type ServerEventOf<K extends EventType> = { $type: K } & EventMap[K];");
    }

    private void WriteEventEntry(Event ev)
    {
        string name = ev.Name.UpperCamelCase;
        string flat = $"{name}: {ObjectType(ev.Properties)};";
        if (Fits(flat))
        {
            _textWriter.WriteLine(flat);
            return;
        }

        using (Scope _ = _textWriter.Scope($"{name}:", ScopeStyle.Curly, ";"))
        {
            foreach (Property property in ev.Properties)
            {
                WriteProperty(property);
            }
        }
    }

    private void EmitGameData(DtoModel model)
    {
        if (model.DropTables.Count == 0 && model.Activities.Count == 0)
        {
            return;
        }

        string itemId = EnumTypeOrString(model, ItemIdEnumName);
        string skillId = EnumTypeOrString(model, SkillIdEnumName);
        string dropTableId = EnumTypeOrString(model, DropTableIdEnumName);

        WriteInterface("ItemReward", "kind: 'item';", "count: number;", "weight: number | null;",
            $"item: {itemId};");
        WriteInterface("TableReward", "kind: 'table';", "count: number;", "weight: number | null;",
            $"table: {dropTableId};");
        WriteInterface("XpReward", "kind: 'xp';", "count: number;", "weight: number | null;",
            $"skill: {skillId};");

        Separate();
        WriteUnion("export type Reward", new[] { "ItemReward", "TableReward", "XpReward" });

        WriteInterface("LevelRequirement", $"skill: {skillId};", "count: number;");
        WriteInterface("DropTableDefinition", "rewards: Reward[];");
        WriteInterface("ActivityDefinition", "rewards: Reward[];",
            "requirements: LevelRequirement[];");

        // The maps are keyed by names narrower than the generated DropTableId
        // and ActivityId enums, which always carry a `None` member that no
        // <DropTable> or <Activity> declares and the maps therefore lack.
        Separate();
        WriteUnion("export type DropTableName",
            model.DropTables.Values.Select(table => Quote(table.Name.UpperCamelCase)).ToList());
        Separate();
        WriteUnion("export type ActivityName",
            model.Activities.Values.Select(activity => Quote(activity.Name.UpperCamelCase)).ToList());

        EmitDropTableData(model);
        EmitActivityData(model);
    }

    private void EmitDropTableData(DtoModel model)
    {
        const string declaration =
            "export const DROP_TABLE_DATA: Record<DropTableName, DropTableDefinition> =";

        Separate();
        if (model.DropTables.Count == 0)
        {
            _textWriter.WriteLine($"{declaration} {{}};");
            return;
        }

        using (Scope _ = _textWriter.Scope(declaration, ScopeStyle.Curly, ";"))
        {
            List<DropTable> tables = model.DropTables.Values.ToList();
            for (int i = 0; i < tables.Count; i++)
            {
                string separator = i == tables.Count - 1 ? "" : ",";
                string key = tables[i].Name.UpperCamelCase;
                using (Scope __ = _textWriter.Scope($"{key}:", ScopeStyle.Curly, separator))
                {
                    WriteArray("rewards: ", tables[i].Rewards.Select(RewardLiteral).ToList(), "",
                        elementsAreObjects: true);
                }
            }
        }
    }

    private void EmitActivityData(DtoModel model)
    {
        const string declaration =
            "export const ACTIVITY_DATA: Record<ActivityName, ActivityDefinition> =";

        Separate();
        if (model.Activities.Count == 0)
        {
            _textWriter.WriteLine($"{declaration} {{}};");
            return;
        }

        using (Scope _ = _textWriter.Scope(declaration, ScopeStyle.Curly, ";"))
        {
            List<Activity> activities = model.Activities.Values.ToList();
            for (int i = 0; i < activities.Count; i++)
            {
                Activity activity = activities[i];
                string separator = i == activities.Count - 1 ? "" : ",";
                string key = activity.Name.UpperCamelCase;
                using (Scope __ = _textWriter.Scope($"{key}:", ScopeStyle.Curly, separator))
                {
                    WriteArray("rewards: ", activity.Rewards.Select(RewardLiteral).ToList(), ",",
                        elementsAreObjects: true);
                    WriteArray("requirements: ",
                        activity.Requirements.Select(RequirementLiteral).ToList(), "",
                        elementsAreObjects: true);
                }
            }
        }
    }

    private void WriteInterface(string name, params string[] members)
    {
        Separate();
        using (Scope _ = _textWriter.Scope($"export interface {name}"))
        {
            foreach (string member in members)
            {
                _textWriter.WriteLine(member);
            }
        }
    }

    /// <summary>
    /// Prettier gives a union three forms: flat when the whole declaration fits,
    /// then every member on one indented line with no leading pipe, then one
    /// leading-pipe member per line.
    /// </summary>
    private void WriteUnion(string declaration, IReadOnlyList<string> members)
    {
        if (members.Count == 0)
        {
            _textWriter.WriteLine($"{declaration} = never;");
            return;
        }

        string joined = string.Join(" | ", members);
        if (Fits($"{declaration} = {joined};"))
        {
            _textWriter.WriteLine($"{declaration} = {joined};");
            return;
        }

        _textWriter.WriteLine($"{declaration} =");
        using (Scope _ = new(ScopeStyle.Indentation, _textWriter))
        {
            if (Fits($"{joined};"))
            {
                _textWriter.WriteLine($"{joined};");
                return;
            }

            for (int i = 0; i < members.Count; i++)
            {
                string terminator = i == members.Count - 1 ? ";" : "";
                _textWriter.WriteLine($"| {members[i]}{terminator}");
            }
        }
    }

    /// <param name="elementsAreObjects">Whether every element is an object
    /// literal with more than one property. Prettier force-breaks an array of
    /// two or more of those whatever its width, so such an array never gets the
    /// flat form.</param>
    private void WriteArray(string prefix, IReadOnlyList<string> elements, string suffix,
        bool elementsAreObjects)
    {
        if (elements.Count == 0)
        {
            _textWriter.WriteLine($"{prefix}[]{suffix}");
            return;
        }

        string flat = $"{prefix}[{string.Join(", ", elements)}]{suffix}";
        bool forceBreak = elementsAreObjects && elements.Count > 1;
        if (!forceBreak && Fits(flat))
        {
            _textWriter.WriteLine(flat);
            return;
        }

        _textWriter.WriteLine($"{prefix}[");
        using (Scope _ = new(ScopeStyle.Indentation, _textWriter))
        {
            for (int i = 0; i < elements.Count; i++)
            {
                string separator = i == elements.Count - 1 ? "" : ",";
                _textWriter.WriteLine($"{elements[i]}{separator}");
            }
        }
        _textWriter.WriteLine($"]{suffix}");
    }

    private void WriteProperty(Property property)
    {
        _textWriter.WriteLine($"{PropertySignature(property)};");
    }

    private bool Fits(string text)
    {
        return _textWriter.Indentations * TabWidth + text.Length <= PrintWidth;
    }

    private static string ObjectType(IReadOnlyList<Property> properties)
    {
        // Not `{}`: that type accepts any non-nullish value, so a wrong payload
        // would still type-check, and it is what no-empty-object-type flags.
        return properties.Count == 0
            ? "Record<string, never>"
            : "{ " + string.Join("; ", properties.Select(PropertySignature)) + " }";
    }

    private static string PropertySignature(Property property)
    {
        string optional = property.Optional ? "?" : "";
        return $"{property.Name.LowerCamelCase}{optional}: {GetPropertyType(property)}";
    }

    private static string RewardLiteral(Reward reward)
    {
        return reward switch
        {
            ItemReward item =>
                $"{{ kind: 'item', count: {item.Count}, weight: {WeightLiteral(item.Weight)}, item: {Quote(new Casing(item.Item).UpperCamelCase)} }}",
            TableReward table =>
                $"{{ kind: 'table', count: {table.Count}, weight: {WeightLiteral(table.Weight)}, table: {Quote(new Casing(table.Table).UpperCamelCase)} }}",
            XpReward xp =>
                $"{{ kind: 'xp', count: {xp.Count}, weight: {WeightLiteral(xp.Weight)}, skill: {Quote(new Casing(xp.Skill).UpperCamelCase)} }}",
            _ => throw new NotSupportedException("Reward expressions should drop a table, an item or xp."),
        };
    }

    private static string RequirementLiteral(LevelRequirement requirement)
    {
        string skill = Quote(new Casing(requirement.Skill).UpperCamelCase);
        return $"{{ skill: {skill}, count: {requirement.Count} }}";
    }

    private static string WeightLiteral(float? weight)
    {
        return weight is null ? "null" : weight.Value.ToString(CultureInfo.InvariantCulture);
    }

    /// <summary>
    /// The game data references the item, skill and drop table enums by name.
    /// Nothing forces a contract to declare them, so fall back to `string`
    /// rather than emitting a reference to a type that was never generated.
    /// </summary>
    private static string EnumTypeOrString(DtoModel model, string enumName)
    {
        return model.Enums.ContainsKey(enumName) ? enumName : "string";
    }

    private static string Quote(string value)
    {
        return $"'{value}'";
    }

    private static string BaseType(Object obj)
    {
        return obj switch
        {
            Dto => "DtoBase",
            Event => "EventBase",
            Request => "RequestBase",
            Response => "ResponseBase",
            _ => throw new ArgumentOutOfRangeException(nameof(obj))
        };
    }

    private static string GetPropertyType(Property property)
    {
        if (property is CustomProperty custom)
        {
            string str = custom.Type.Name.UpperCamelCase;
            return custom.Multiple ? str + "[]" : str;
        }

        string builtIn = property.PropertyType switch
        {
            PropertyType.String => "string",
            PropertyType.Int => "number",
            PropertyType.Float => "number",
            PropertyType.Guid => "string",
            PropertyType.UserId => "string",
            PropertyType.ProfileId => "string",
            PropertyType.Timestamp => "number",
            _ => throw new ArgumentOutOfRangeException()
        };
        return property.Multiple ? builtIn + "[]" : builtIn;
    }
}