using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace Generator.Core;

/// <summary>
/// Emits the contract as a TypeScript <em>value</em> rather than as declarations.
///
/// TsEmitter's interfaces are erased at compile time, so nothing at runtime can ask what
/// properties a request has. The debug console needs exactly that — it builds an input form
/// per request — so this emitter writes the same model out as data.
///
/// The point of generating it, rather than parsing types.xml in the browser, is that every
/// rule the console depends on already lives here: the casing split, the Dto/Request/
/// Response/Event suffixes, the implicit None enum member, and the DropTableId/ActivityId
/// enums synthesised from &lt;DropTable&gt;/&lt;Activity&gt;. A second implementation of those
/// is only correct until one of them changes.
///
/// Layout is written by hand rather than through ScopedTextWriter.Scope, which puts the
/// brace on its own line — right for a declaration, wrong for an object literal.
/// </summary>
public sealed class TsSchemaEmitter : IDtoEmitter
{
    /// <summary>
    /// Where the hand-written interfaces live, relative to the emitted file. The explicit
    /// annotation they provide is what makes a mismatch between this emitter and its
    /// consumer a type error instead of a runtime surprise.
    /// </summary>
    private const string SchemaModule = "./schema";

    private readonly TextWriter _writer;
    private int _indent;

    public TsSchemaEmitter(TextWriter writer)
    {
        _writer = writer;
    }

    public void EmitDtos(DtoModel model)
    {
        _writer.WriteLine("// <auto-generated/>");
        _writer.WriteLine("// Generated from types.xml by Generators/Core/TsSchemaEmitter.cs.");
        _writer.WriteLine("// Run `bun run generate` in Frontend/ to refresh it; do not edit by hand.");
        _writer.WriteLine();
        _writer.WriteLine($"import type {{ ProtocolSchema }} from '{SchemaModule}';");
        _writer.WriteLine();

        Open("export const PROTOCOL: ProtocolSchema = {");
        EmitEnums(model);
        EmitDtoRecord(model);
        EmitRequests(model);
        EmitEvents(model);
        Close("};");
    }

    private void EmitEnums(DtoModel model)
    {
        Open("enums: {");
        foreach (Enum en in model.Enums.Values)
        {
            string name = en.Name.UpperCamelCase;
            string values = string.Join(", ", en.GetEnums().Select(v => Quote(v.Name.UpperCamelCase)));
            Line($"{name}: {{ typeName: {Quote(name)}, values: [{values}] }},");
        }
        Close("},");
    }

    private void EmitDtoRecord(DtoModel model)
    {
        Open("dtos: {");
        foreach (Dto dto in model.Dtos.Values)
        {
            EmitObject(dto, $"{dto.Name.UpperCamelCase}: {{");
        }
        Close("},");
    }

    private void EmitRequests(DtoModel model)
    {
        Open("requests: [");
        foreach (Request request in model.Requests.Values)
        {
            Open("{");
            Line($"typeName: {Quote(request.Name.UpperCamelCase)},");
            EmitProperties(request);
            EmitObject(request.Response, "response: {");
            Close("},");
        }
        Close("],");
    }

    private void EmitEvents(DtoModel model)
    {
        Open("events: [");
        foreach (Event ev in model.Events.Values)
        {
            EmitObject(ev, "{");
        }
        Close("]");
    }

    /// <summary>Writes a `{ typeName, properties }` pair, opened by the given line.</summary>
    private void EmitObject(Object obj, string opening)
    {
        Open(opening);
        Line($"typeName: {Quote(obj.Name.UpperCamelCase)},");
        EmitProperties(obj);
        Close("},");
    }

    private void EmitProperties(Object obj)
    {
        if (obj.Properties.Count == 0)
        {
            // On one line: an empty array spread over three is noise in a file whose main
            // use is being diffed against the previous generation.
            Line("properties: [],");
            return;
        }

        Open("properties: [");
        foreach (Property property in obj.Properties)
        {
            IEnumerable<string> fields =
            [
                $"name: {Quote(property.Name.UpperCamelCase)}",
                $"wireName: {Quote(property.Name.LowerCamelCase)}",
                $"kind: {Quote(Kind(property))}",
                $"typeName: {Quote(TypeName(property))}",
                $"multiple: {Literal(property.Multiple)}",
                $"optional: {Literal(property.Optional)}",
            ];
            Line($"{{ {string.Join(", ", fields)} }},");
        }
        Close("],");
    }

    /// <summary>
    /// The discriminator the console switches on to choose an input control. A custom
    /// property splits by what it resolved to, because an enum renders as a dropdown of its
    /// members while a DTO recurses into a nested form.
    /// </summary>
    private static string Kind(Property property)
    {
        if (property is CustomProperty custom)
        {
            return custom.Type is Enum ? "enum" : "dto";
        }

        return property.PropertyType switch
        {
            PropertyType.String => "string",
            PropertyType.Int => "int",
            PropertyType.Float => "float",
            PropertyType.Guid => "guid",
            PropertyType.UserId => "userId",
            PropertyType.ProfileId => "profileId",
            // The kind names the wire primitive and so the input control; the
            // semantic token (Timestamp) survives as typeName, which labels the field.
            PropertyType.Timestamp => "long",
            _ => throw new ArgumentOutOfRangeException(nameof(property), property.PropertyType,
                "Unhandled property type."),
        };
    }

    /// <summary>
    /// For a custom property, the generated type name — which for a DTO already carries its
    /// `Dto` suffix, because the model appends it when the type is constructed. For a
    /// built-in, the token as written in types.xml, which is what the form shows as a label.
    /// </summary>
    private static string TypeName(Property property)
    {
        return property is CustomProperty custom
            ? custom.Type.Name.UpperCamelCase
            : property.PropertyTypeString.UpperCamelCase;
    }

    private static string Literal(bool value)
    {
        return value ? "true" : "false";
    }

    /// <summary>
    /// Single-quoted to match the frontend's Prettier config. Every name reaching here has
    /// been through Casing, which yields letters and digits only, so the escaping covers the
    /// impossible rather than the expected — but a generator that can emit a broken string
    /// literal is worse than one that escapes needlessly.
    /// </summary>
    private static string Quote(string value)
    {
        return $"'{value.Replace("\\", "\\\\").Replace("'", "\\'")}'";
    }

    private void Line(string text)
    {
        _writer.Write(new string('\t', _indent));
        _writer.WriteLine(text);
    }

    private void Open(string text)
    {
        Line(text);
        _indent++;
    }

    private void Close(string text)
    {
        _indent--;
        Line(text);
    }

    public void Dispose()
    {
    }
}
