// Mirrors the backend wire protocol (types.xml -> Backend/Dtos, generated by
// Generators/Core/CsEmitter.cs). JSON text frames where "$type" is the exact C#
// class name. Every other property is camelCase:
// the generator stamps an explicit [JsonPropertyName] on each one, and
// SocketJsonSerializer sets PropertyNamingPolicy = CamelCase on top of that.
// Requests carry a client-chosen `requestId` that the matching response echoes
// back. Server-push events never carry a `requestId`; the backend stamps each
// with a per-socket `eventId` (first is 0) and a Unix-ms `timestamp` at send.

export interface ProfileDto {
	name: string;
	profileId: string;
}

export interface PongResponse {
	$type: 'PongResponse';
	requestId: number;
}

export interface LoginAsTestUserResponse {
	$type: 'LoginAsTestUserResponse';
	requestId: number;
}

export interface CreateProfileResponse {
	$type: 'CreateProfileResponse';
	requestId: number;
}

export interface ListProfilesResponse {
	$type: 'ListProfilesResponse';
	requestId: number;
	profiles: ProfileDto[];
}

export interface SelectProfileResponse {
	$type: 'SelectProfileResponse';
	requestId: number;
}

/**
 * The backend echoes the id of the request that failed. A frame it could not
 * even deserialize has no id to echo, and Socket.HandleTextMessageAsync sends 0
 * in that case — an id no request ever has, since they start at 1.
 */
export interface ErrorResponse {
	$type: 'ErrorResponse';
	requestId: number;
	message: string;
}

export type ServerResponse =
	| PongResponse
	| LoginAsTestUserResponse
	| CreateProfileResponse
	| ListProfilesResponse
	| SelectProfileResponse;

// Any server-push message: an EventBase subclass, which carries no requestId.
export interface ServerEvent {
	$type: string;
	/** The backend's per-socket sequence, stamped at send; the first event is 0. */
	eventId: number;
	/** Unix epoch milliseconds, stamped by the backend at send. */
	timestamp: number;
	[key: string]: unknown;
}

/*
 * Server-push messages, mirroring RequestMap. The backend names them
 * `<Noun>ChangedEvent` and puts the full replacement state in them rather than a
 * delta, so a handler can overwrite its slice without reconciling.
 *
 * TODO: ProfilesChangedEvent is sent by AuthController.CreateProfile but nothing
 * dispatches it yet. Two things about it will matter when it is wired up: it
 * arrives *before* the response to the request that caused it, and it makes
 * createProfile's refetch redundant.
 */
export type EventMap = {
	ProfilesChangedEvent: { profiles: ProfileDto[] };
};

export type EventType = keyof EventMap;

// The EventBase stamps are repeated here so a typed event stays assignable to
// ServerEvent, which the handler-set casts in WsClient.onEvent rely on.
export type ServerEventOf<K extends EventType> = {
	$type: K;
	eventId: number;
	timestamp: number;
} & EventMap[K];

export type RequestMap = {
	PingRequest: { payload: Record<string, never>; response: PongResponse };
	LoginAsTestUserRequest: { payload: Record<string, never>; response: LoginAsTestUserResponse };
	CreateProfileRequest: { payload: { name: string }; response: CreateProfileResponse };
	ListProfilesRequest: { payload: Record<string, never>; response: ListProfilesResponse };
	SelectProfileRequest: { payload: { profileId: string }; response: SelectProfileResponse };
};

export type RequestType = keyof RequestMap;

// The backend reads a single 1 KiB frame and rejects anything larger.
export const MAX_MESSAGE_BYTES = 1024;

export function encodeRequest<K extends RequestType>(
	type: K,
	id: number,
	payload: RequestMap[K]['payload']
): string;
/**
 * The untyped form, for a request this file does not describe. The debug console
 * builds its catalogue from the backend's own types.xml, which is always at least
 * as current as RequestMap.
 */
export function encodeRequest(type: string, id: number, payload: Record<string, unknown>): string;
export function encodeRequest(type: string, id: number, payload: Record<string, unknown>): string {
	// $type is inserted first, and JSON.stringify preserves insertion order.
	// Not load-bearing any more — SocketJsonSerializer sets
	// AllowOutOfOrderMetadataProperties — but it is what System.Text.Json reads
	// fastest, and it puts the discriminator where a human reading a frame in the
	// console looks for it.
	const json = JSON.stringify({ $type: type, requestId: id, ...payload });
	if (new TextEncoder().encode(json).length > MAX_MESSAGE_BYTES) {
		throw new Error(`Encoded ${type} exceeds the backend's ${MAX_MESSAGE_BYTES}-byte frame limit`);
	}
	return json;
}

/**
 * The `requestId` in a frame, or null when the text is not JSON, is not an
 * object, or carries no numeric id. For a frame this side did not build — the
 * debug console sends its editor's text verbatim, malformations included — so
 * it reads what is there rather than assuming a well-formed request.
 */
export function readRequestId(raw: string): number | null {
	try {
		const parsed: unknown = JSON.parse(raw);
		if (typeof parsed !== 'object' || parsed === null) {
			return null;
		}
		const id = (parsed as { requestId?: unknown }).requestId;
		return typeof id === 'number' ? id : null;
	} catch {
		return null;
	}
}

export type Classified =
	| { kind: 'response'; id: number; message: ServerResponse }
	| { kind: 'error'; message: ErrorResponse }
	| { kind: 'event'; message: ServerEvent }
	| { kind: 'unknown'; raw: string };

export function classifyMessage(raw: string): Classified {
	let parsed: unknown;
	try {
		parsed = JSON.parse(raw);
	} catch {
		return { kind: 'unknown', raw };
	}
	if (typeof parsed !== 'object' || parsed === null || !('$type' in parsed)) {
		return { kind: 'unknown', raw };
	}
	const message = parsed as { $type: string; requestId?: number | null };
	if (message.$type === 'ErrorResponse') {
		return { kind: 'error', message: message as unknown as ErrorResponse };
	}
	if (typeof message.requestId === 'number') {
		return { kind: 'response', id: message.requestId, message: message as ServerResponse };
	}
	// A known response type without a numeric requestId is a malformed response,
	// not a server event: genuine events carry their own $type and never appear
	// in RESPONSE_TYPES.
	if (RESPONSE_TYPES.has(message.$type)) {
		return { kind: 'unknown', raw };
	}
	return { kind: 'event', message: message as ServerEvent };
}

// Keep in sync with the ServerResponse union above: a requestId-less frame whose
// $type is one of these answers a request and must not be read as an event.
const RESPONSE_TYPES = new Set<string>([
	'PongResponse',
	'LoginAsTestUserResponse',
	'CreateProfileResponse',
	'ListProfilesResponse',
	'SelectProfileResponse'
]);
