using System;
using System.Collections.Immutable;
using System.IO;
using System.Text;
using System.Xml;
using System.Xml.Serialization;
using Generator.Core;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Backend.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class TypesGenerator : IIncrementalGenerator
{
    private const string TypesFileName = "types.xml";
    private const string DtoOutputName = "Dto.g.cs";
    private const string SchemaOutputName = "ProtocolSchema.g.cs";

    private static readonly DiagnosticDescriptor DtoFileMissing = new(
        id: "DTC001",
        title: "DTO file is missing",
        messageFormat: "No file named '{0}' was found among the project's AdditionalFiles",
        category: "Dto",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor ParseError = new(
        id: "DTC002",
        title: "DTO file is invalid",
        messageFormat: "{0}",
        category: "Dto",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValueProvider<ImmutableArray<string>> contractXml = context.AdditionalTextsProvider
            .Where(file =>
                string.Equals(Path.GetFileName(file.Path), TypesFileName, StringComparison.OrdinalIgnoreCase))
            .Select((file, _) => file.GetText()?.ToString() ?? string.Empty)
            .Collect()
            .WithTrackingName("DtoContractXml");

        context.RegisterSourceOutput(contractXml, static (productionContext, xml) =>
        {
            if (xml.IsEmpty)
            {
                productionContext.ReportDiagnostic(
                    Diagnostic.Create(DtoFileMissing, Location.None, TypesFileName));
                return;
            }

            TypesXmlRoot root;
            try
            {
                byte[] bytes = Encoding.UTF8.GetBytes(xml[0]);
                using MemoryStream stream = new(bytes);
                XmlSerializer serializer = new(typeof(TypesXmlRoot));
                root = (TypesXmlRoot)serializer.Deserialize(stream)!;
            }
            catch (InvalidOperationException ex) when (ex.InnerException is XmlException xmlEx)
            {
                productionContext.ReportDiagnostic(
                    Diagnostic.Create(ParseError, Location.None, xmlEx.Message));
                return;
            }

            AddEnumsVisitor enumsVisitor = new();
            root.Accept(enumsVisitor);

            using StringWriter writer = new();
            using (CsEmitterVisitor csEmitter = new(writer))
            {
                csEmitter.Emit(root);
            }

            productionContext.AddSource(DtoOutputName, SourceText.From(writer.ToString(), Encoding.UTF8));

            string schemaSource =
                "// <auto-generated/>\n" +
                "#nullable enable\n" +
                "namespace Backend.Dtos;\n" +
                "\n" +
                "public static class ProtocolSchemaJson\n" +
                "{\n" +
                "    public const string Base64 = \"" +
                Convert.ToBase64String(Encoding.UTF8.GetBytes(JsonSchemaEmitter.Emit(root))) +
                "\";\n" +
                "}\n";

            productionContext.AddSource(SchemaOutputName, SourceText.From(schemaSource, Encoding.UTF8));
        });
    }
}
