<script lang="ts">
	import { cn, type WithElementRef } from '$lib/utils/stylingUtils.js';
	import type { HTMLInputAttributes, HTMLInputTypeAttribute } from 'svelte/elements';

	/*
	 * Generated by `shadcn-svelte add input`, then re-tabled against the OpenIdle
	 * design system the way button.svelte was. `shadcn-svelte update` would
	 * overwrite this file, so treat it as a local fork.
	 *
	 * The design system has no Input of its own to transcribe from, so the styling
	 * is derived from Button's vocabulary instead: the same control padding, so a
	 * field and the button beside it share a height; the recessed treatment the
	 * design gives every inset surface (bg-surface-inset over --inset-well); and
	 * Button's focus ruling — an offset outline rather than shadcn's ring, because
	 * a box-shadow cannot be offset.
	 *
	 * Two further departures from the generator, both matching Button:
	 * - `disabled:pointer-events-none` is dropped, because it would inherit the
	 *   parent's cursor instead of showing `not-allowed`.
	 * - The `type="file"` branch is gone along with its `file:*` classes. The
	 *   design has no file input, and a second copy of the class string for it is
	 *   the kind of unused variant Button also shed.
	 */
	type Props = WithElementRef<
		Omit<HTMLInputAttributes, 'type'> & { type?: Exclude<HTMLInputTypeAttribute, 'file'> }
	>;

	let {
		ref = $bindable(null),
		value = $bindable(),
		type,
		class: className,
		'data-slot': dataSlot = 'input',
		...restProps
	}: Props = $props();
</script>

<input
	bind:this={ref}
	data-slot={dataSlot}
	class={cn(
		'oi-body-md w-full min-w-0 rounded-sm border border-line-soft bg-surface-inset px-(--pad-control-x) py-(--pad-control-y) text-text-strong shadow-(--inset-well) transition-[border-color,color] duration-(--dur-fast) ease-out placeholder:text-text-faint focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring disabled:cursor-not-allowed disabled:opacity-42 aria-invalid:border-(--crimson-500)',
		className
	)}
	{type}
	bind:value
	{...restProps}
/>
