using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using Generator.Core.Spec;

namespace Generator.Core;

public sealed class CsEmitterVisitor : VisitorBase, IDisposable
{
    private enum Section { None, DropTable, Activity, Tool }

    private readonly ScopedTextWriter _textWriter;
    private readonly List<string> _allObjects = new();
    private readonly List<(string name, List<Property> properties)> _inlineResponses = new();
    private Section _currentSection;
    private Scope? _classScope;
    private Scope? _methodScope;

    public CsEmitterVisitor(TextWriter writer)
    {
        writer.WriteLine("// <auto-generated/>");
        writer.WriteLine("#nullable enable");
        writer.WriteLine("using System;");
        writer.WriteLine("using System.Text.Json.Serialization;");
        writer.WriteLine("using Backend.Services;");
        writer.WriteLine();
        writer.WriteLine("namespace Backend.Dtos;");
        writer.WriteLine();

        _textWriter = new ScopedTextWriter(writer);
    }

    public override void Visit(Spec.Enum xmlEnum) => EmitEnum(xmlEnum);

    public override void Visit(DropTable xmlDropTable)
    {
        EnsureSection(Section.DropTable, "public static class DropTableData", "public static void AddAll(DropTableService service)");
        EmitDropTable(xmlDropTable);
    }

    public override void Visit(Activity xmlActivity)
    {
        EnsureSection(Section.Activity, "public static class ActivityData", "public static void AddAll(ActivityService service)");
        EmitActivity(xmlActivity);
    }

    public override void Visit(Item xmlItem)
    {
        EnsureSection(Section.Tool, "public static class ToolData", "public static void AddAll(ToolService service)");
        EmitItem(xmlItem);
    }

    public override void Visit(Skill xmlSkill)
    {
        if (xmlSkill.Slots.Count == 0)
        {
            return;
        }

        EnsureSection(Section.Tool, "public static class ToolData", "public static void AddAll(ToolService service)");
        EmitSkillSlots(xmlSkill);
    }

    public override void Visit(Dto xmlDto)
    {
        CloseSection();
        EmitObject(xmlDto.Name, "DtoBase", xmlDto.Properties);
    }

    public override void Visit(Request xmlRequest)
    {
        CloseSection();
        EmitObject(xmlRequest.Name, "RequestBase", xmlRequest.Properties);

        if (xmlRequest.Response.Name == null)
        {
            _inlineResponses.Add((xmlRequest.Name + "Response", xmlRequest.Response.Properties));
        }
    }

    public override void Visit(Response xmlResponse)
    {
        if (xmlResponse.Name != null)
        {
            CloseSection();
            EmitObject(xmlResponse.Name, "ResponseBase", xmlResponse.Properties);
        }
    }

    public override void Visit(Event xmlEvent)
    {
        CloseSection();
        EmitObject(xmlEvent.Name, "EventBase", xmlEvent.Properties);
    }

    public void Emit(Root root) => root.Accept(this);

    public void Dispose()
    {
        CloseSection();

        foreach ((string name, List<Property> properties) in _inlineResponses)
        {
            EmitObject(name, "ResponseBase", properties);
        }

        EmitBaseClasses();
    }

    private void EnsureSection(Section section, string className, string methodSignature)
    {
        if (_currentSection == section)
        {
            return;
        }

        CloseSection();
        _textWriter.WriteLine();
        _classScope = _textWriter.Scope(className);
        _methodScope = _textWriter.Scope(methodSignature);
        _currentSection = section;
    }

    private void CloseSection()
    {
        _methodScope?.Dispose();
        _methodScope = null;
        _classScope?.Dispose();
        _classScope = null;
        _currentSection = Section.None;
    }

    private void EmitEnum(Spec.Enum xmlEnum)
    {
        using (Scope _ = _textWriter.Scope($"public enum {xmlEnum.Name}"))
        {
            foreach (string name in xmlEnum.Values.Select(value => value.Name).Distinct())
            {
                _textWriter.WriteLine($"{name},");
            }
        }
    }

    private void EmitDropTable(DropTable dropTable)
    {
        List<Reward> rewards = Rewards(dropTable.ItemRewards, dropTable.TableRewards, dropTable.XpRewards);
        _textWriter.Write($"service.AddDropTable(DropTableId.{dropTable.Name}, new DropTable(");
        if (rewards.Count > 0)
        {
            _textWriter.WriteLine();
            using (Scope _ = new(ScopeStyle.Indentation, _textWriter))
            {
                for (int i = 0; i < rewards.Count; i++)
                {
                    string separator = i < rewards.Count - 1 ? "," : "";
                    _textWriter.WriteLine($"{RewardExpression(rewards[i])}{separator}");
                }
            }
        }
        _textWriter.WriteLine("));");
    }

    private void EmitActivity(Activity activity)
    {
        string rewards = string.Join(", ", Rewards(activity.ItemRewards, activity.TableReward, activity.XpRewards).Select(RewardExpression));
        string requirements = string.Join(", ", activity.LevelRequirements.Select(RequirementExpression));
        string costs = string.Join(", ", activity.ItemCosts.Select(ItemCostExpression));
        _textWriter.WriteLine(
            $"service.AddActivity(ActivityId.{activity.Name}, new ActivityDefinition(time: {TimeLiteral(activity.Time)}, rewards: [{rewards}], requirements: [{requirements}], costs: [{costs}]));");
    }

    private void EmitItem(Item item)
    {
        string tags = string.Join(", ", item.Tags.Select(tag => $"ItemTagId.{tag.Name}"));
        string stats = string.Join(", ", item.Stats.Select(ItemStatExpression));
        _textWriter.WriteLine(
            $"service.AddItem(ItemId.{item.Name}, new ItemDefinition(tags: [{tags}], stats: [{stats}]));");
    }

    private void EmitSkillSlots(Skill skill)
    {
        string slots = string.Join(", ", skill.Slots.Select(SlotExpression));
        _textWriter.WriteLine(
            $"service.AddSkillSlots(SkillId.{skill.Name}, [{slots}]);");
    }

    private void EmitObject(string name, string baseType, List<Property> properties)
    {
        using (Scope _ = _textWriter.Scope($"public sealed class {name} : {baseType}"))
        {
            foreach (Property property in properties)
            {
                EmitProperty(property);
            }
        }
        _textWriter.WriteLine();

        _allObjects.Add(name);
    }

    private void EmitProperty(Property property, string setter = "init")
    {
        _textWriter.WriteLine($"[JsonPropertyName(\"{property.Name.ToCamelCase()}\")]");
        _textWriter.WriteLine($"{GetPropertyModifiers(property)} {GetPropertyType(property)} {property.Name} {{ get; {setter}; }}");
    }

    private static string GetPropertyModifiers(Property property)
    {
        string str = "public";
        if (!property.Optional)
        {
            str += " required";
        }
        return str;
    }

    private static string GetPropertyType(Property property)
    {
        string type = property.Type.ToLowerInvariant() switch
        {
            "string" => "string",
            "int" => "int",
            "float" => "float",
            "guid" or "userid" or "profileid" => "Guid",
            "timestamp" => "long",
            _ => property.Type,
        };
        if (property.Multiple)
            type += "[]";
        if (property.Optional)
            type += "?";
        return type;
    }

    private static string RewardExpression(Reward reward) => reward switch
    {
        ItemReward itemReward =>
            $"new ItemReward({itemReward.Count}, {WeightLiteral(itemReward.Weight)}, ItemId.{itemReward.Item})",
        TableReward tableReward =>
            $"new TableReward({tableReward.Count}, {WeightLiteral(tableReward.Weight)}, DropTableId.{tableReward.Table})",
        XpReward xpReward =>
            $"new XpReward({xpReward.Count}, {WeightLiteral(xpReward.Weight)}, SkillId.{xpReward.Skill})",
        _ => throw new NotSupportedException("Reward expressions should drop a table, an item or xp."),
    };

    private static string RequirementExpression(LevelRequirement requirement) =>
        $"new LevelRequirement(SkillId.{requirement.Skill}, {requirement.Count})";

    private static string ItemCostExpression(ItemCost cost) =>
        $"new ItemCost({cost.Cost}, ItemId.{cost.Item})";

    private static string ItemStatExpression(ItemStat stat) =>
        $"new ItemStat(ToolStat.{stat.Name}, {stat.Value.ToString(CultureInfo.InvariantCulture)}f)";

    private static string SlotExpression(Slot slot) =>
        $"new SlotBinding(ItemSlotId.{slot.Name}, ItemTagId.{slot.AcceptedTag.Name}, {slot.Required.ToString().ToLowerInvariant()})";

    private static string WeightLiteral(float? weight) =>
        weight is null ? "null" : weight.Value.ToString(CultureInfo.InvariantCulture) + "f";

    private static string TimeLiteral(float time) =>
        time.ToString(CultureInfo.InvariantCulture) + "f";

    private static List<Reward> Rewards(
        List<ItemReward> items, List<TableReward> tables, List<XpReward> xps) =>
        items.Cast<Reward>().Concat(tables).Concat(xps).ToList();

    private void EmitBaseClasses()
    {
        _textWriter.WriteLine("[JsonPolymorphic]");
        foreach (string name in _allObjects)
        {
            _textWriter.WriteLine($"[JsonDerivedType(typeof({name}), nameof({name}))]");
        }

        using (Scope _ = _textWriter.Scope("public abstract class DtoBase"))
        {
        }
        _textWriter.WriteLine();

        using (Scope _ = _textWriter.Scope("public abstract class RequestBase : DtoBase"))
        {
            EmitProperty(new Property { Name = "RequestId", Type = "int", Optional = true }, "set");
        }
        _textWriter.WriteLine();

        using (Scope _ = _textWriter.Scope("public abstract class ResponseBase : DtoBase"))
        {
            EmitProperty(new Property { Name = "RequestId", Type = "int", Optional = true }, "set");
        }
        _textWriter.WriteLine();

        using (Scope _ = _textWriter.Scope("public abstract class EventBase : DtoBase"))
        {
            EmitProperty(new Property { Name = "EventId", Type = "int", Optional = true }, "set");
            EmitProperty(new Property { Name = "Timestamp", Type = "timestamp", Optional = true }, "set");
        }
        _textWriter.WriteLine();
    }
}
