using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using Generator.Core.Spec;

namespace Generator.Core;

public sealed class TsEmitterVisitor : VisitorBase, IDisposable
{
    private const int PrintWidth = 100;
    private const int TabWidth = 2;

    private readonly ScopedTextWriter _textWriter;
    private bool _firstBlock = true;

    private readonly List<Spec.Enum> _enums = new();
    private readonly List<Dto> _dtos = new();
    private readonly List<Request> _requests = new();
    private readonly List<Event> _events = new();
    private readonly List<DropTable> _dropTables = new();
    private readonly List<Activity> _activities = new();
    private readonly List<(string Name, List<Property> Properties)> _namedResponses = new();

    public TsEmitterVisitor(TextWriter writer)
    {
        writer.NewLine = "\n";
        _textWriter = new ScopedTextWriter(writer)
        {
            IndentUnit = "\t",
            BraceStyle = BraceStyle.SameLine,
        };

        _textWriter.WriteLine("// <auto-generated>");
        _textWriter.WriteLine("//     Generated from types.xml by Generators/Core/TsEmitterVisitor.cs.");
        _textWriter.WriteLine("//     Run `bun run gen:dto` to regenerate; edits are lost on the next run.");
        _textWriter.WriteLine("// </auto-generated>");

        EmitBases();
    }

    public override void Visit(Spec.Enum xmlEnum) => _enums.Add(xmlEnum);
    public override void Visit(Dto xmlDto) => _dtos.Add(xmlDto);
    public override void Visit(Request xmlRequest) => _requests.Add(xmlRequest);
    public override void Visit(Event xmlEvent) => _events.Add(xmlEvent);
    public override void Visit(DropTable xmlDropTable) => _dropTables.Add(xmlDropTable);
    public override void Visit(Activity xmlActivity) => _activities.Add(xmlActivity);

    public override void Visit(Response xmlResponse)
    {
        if (xmlResponse.Name != null)
        {
            _namedResponses.Add((xmlResponse.Name, xmlResponse.Properties));
        }
    }

    public void Emit(Root root) => root.Accept(this);

    public void Dispose()
    {
        EmitEnums();
        EmitInterfaces();
        EmitResponseUnion();
        EmitRequestMap();
        EmitEventMap();
        EmitGameData();
    }

    private void Separate()
    {
        if (_firstBlock)
        {
            _firstBlock = false;
            return;
        }

        _textWriter.WriteLine();
    }

    private void EmitBases()
    {
        Separate();
        using (Scope _ = _textWriter.Scope("export interface DtoBase"))
        {
            _textWriter.WriteLine("$type: string;");
        }

        foreach (string name in new[] { "RequestBase", "ResponseBase" })
        {
            Separate();
            using (Scope _ = _textWriter.Scope($"export interface {name} extends DtoBase"))
            {
                _textWriter.WriteLine("requestId?: number;");
            }
        }

        Separate();
        using (Scope _ = _textWriter.Scope("export interface EventBase extends DtoBase"))
        {
            _textWriter.WriteLine("eventId: number;");
            _textWriter.WriteLine("timestamp: number;");
        }
    }

    private void EmitEnums()
    {
        foreach (Spec.Enum en in _enums)
        {
            Separate();
            List<string> members = en.Values.Select(v => Quote(v.Name)).Distinct().ToList();
            WriteUnion($"export type {en.Name}", members);
        }
    }

    private void EmitInterfaces()
    {
        foreach (Dto dto in _dtos)
        {
            EmitInterface(dto.Name, "DtoBase", dto.Properties, isDto: true);
        }

        foreach (Request request in _requests)
        {
            EmitInterface(request.Name, "RequestBase", request.Properties, isDto: false);
        }

        foreach (Event ev in _events)
        {
            EmitInterface(ev.Name, "EventBase", ev.Properties, isDto: false);
        }

        foreach ((string name, List<Property> properties) in _namedResponses)
        {
            EmitInterface(name, "ResponseBase", properties, isDto: false);
        }

        foreach (Request request in _requests)
        {
            if (request.Response.Name == null)
            {
                EmitInterface(request.Name + "Response", "ResponseBase", request.Response.Properties, isDto: false);
            }
        }
    }

    private void EmitInterface(string name, string baseType, List<Property> properties, bool isDto)
    {
        Separate();

        if (isDto && properties.Count == 0)
        {
            _textWriter.WriteLine($"export type {name} = Record<string, never>;");
            return;
        }

        if (isDto)
        {
            using (Scope _ = _textWriter.Scope($"export interface {name}"))
            {
                foreach (Property property in properties)
                {
                    WriteProperty(property);
                }
            }
            return;
        }

        using (Scope _ = _textWriter.Scope($"export interface {name} extends {baseType}"))
        {
            _textWriter.WriteLine($"$type: {Quote(name)};");
            foreach (Property property in properties)
            {
                WriteProperty(property);
            }
        }
    }

    private void WriteProperty(Property property)
    {
        _textWriter.WriteLine($"{PropertySignature(property)};");
    }

    private string PropertySignature(Property property)
    {
        string optional = property.Optional ? "?" : "";
        return $"{property.Name.ToCamelCase()}{optional}: {GetPropertyType(property)}";
    }

    private string GetPropertyType(Property property)
    {
        string type = property.Type.ToLowerInvariant() switch
        {
            "string" => "string",
            "int" => "number",
            "float" => "number",
            "guid" or "userid" or "profileid" => "string",
            "timestamp" => "number",
            _ => property.Type,
        };
        if (property.Multiple)
            type += "[]";
        return type;
    }

    private void EmitResponseUnion()
    {
        List<string> names = new();
        foreach (Request request in _requests)
        {
            if (request.Response.Name != null)
            {
                names.Add(request.Response.Name);
            }
            else
            {
                names.Add(request.Name + "Response");
            }
        }
        foreach ((string name, _) in _namedResponses)
        {
            names.Add(name);
        }

        Separate();
        WriteUnion("export type ServerResponse", names.Distinct().ToList());

        Separate();
        WriteArray("export const RESPONSE_TYPES: ReadonlySet<string> = new Set(",
            names.Distinct().Select(Quote).ToList(), ");");
    }

    private void EmitRequestMap()
    {
        Separate();
        if (_requests.Count == 0)
        {
            _textWriter.WriteLine("export type RequestMap = Record<string, never>;");
        }
        else
        {
            using (Scope _ = _textWriter.Scope("export type RequestMap =", ScopeStyle.Curly, ";"))
            {
                foreach (Request request in _requests)
                {
                    WriteRequestEntry(request);
                }
            }
        }

        Separate();
        _textWriter.WriteLine("export type RequestType = keyof RequestMap;");
    }

    private void WriteRequestEntry(Request request)
    {
        string responseName = request.Response.Name ?? request.Name + "Response";
        string payload = ObjectType(request.Properties);

        string flat = $"{request.Name}: {{ payload: {payload}; response: {responseName} }};";
        if (Fits(flat))
        {
            _textWriter.WriteLine(flat);
            return;
        }

        using (Scope _ = _textWriter.Scope($"{request.Name}:", ScopeStyle.Curly, ";"))
        {
            if (Fits($"payload: {payload};"))
            {
                _textWriter.WriteLine($"payload: {payload};");
            }
            else
            {
                using (Scope __ = _textWriter.Scope("payload:", ScopeStyle.Curly, ";"))
                {
                    foreach (Property property in request.Properties)
                    {
                        WriteProperty(property);
                    }
                }
            }
            _textWriter.WriteLine($"response: {responseName};");
        }
    }

    private void EmitEventMap()
    {
        Separate();
        if (_events.Count == 0)
        {
            _textWriter.WriteLine("export type EventMap = Record<string, never>;");
        }
        else
        {
            using (Scope _ = _textWriter.Scope("export type EventMap =", ScopeStyle.Curly, ";"))
            {
                foreach (Event ev in _events)
                {
                    WriteEventEntry(ev);
                }
            }
        }

        Separate();
        _textWriter.WriteLine("export type EventType = keyof EventMap;");

        Separate();
        _textWriter.WriteLine(
            "export type ServerEventOf<K extends EventType> = { $type: K } & EventBase & EventMap[K];");
    }

    private void WriteEventEntry(Event ev)
    {
        string flat = $"{ev.Name}: {ObjectType(ev.Properties)};";
        if (Fits(flat))
        {
            _textWriter.WriteLine(flat);
            return;
        }

        using (Scope _ = _textWriter.Scope($"{ev.Name}:", ScopeStyle.Curly, ";"))
        {
            foreach (Property property in ev.Properties)
            {
                WriteProperty(property);
            }
        }
    }

    private string ObjectType(List<Property> properties)
    {
        return properties.Count == 0
            ? "Record<string, never>"
            : "{ " + string.Join("; ", properties.Select(PropertySignature)) + " }";
    }

    private void EmitGameData()
    {
        if (_dropTables.Count == 0 && _activities.Count == 0)
        {
            return;
        }

        string itemId = HasEnum("ItemId") ? "ItemId" : "string";
        string skillId = HasEnum("SkillId") ? "SkillId" : "string";
        string dropTableId = HasEnum("DropTableId") ? "DropTableId" : "string";

        WriteInterface("ItemReward", "kind: 'item';", "count: number;", "weight: number | null;",
            $"item: {itemId};");
        WriteInterface("TableReward", "kind: 'table';", "count: number;", "weight: number | null;",
            $"table: {dropTableId};");
        WriteInterface("XpReward", "kind: 'xp';", "count: number;", "weight: number | null;",
            $"skill: {skillId};");

        Separate();
        WriteUnion("export type Reward", new[] { "ItemReward", "TableReward", "XpReward" });

        WriteInterface("LevelRequirement", $"skill: {skillId};", "count: number;");
        WriteInterface("ItemCost", $"item: {itemId};", "count: number;");
        WriteInterface("DropTableDefinition", "rewards: Reward[];");
        WriteInterface("ActivityDefinition", "time: number;", "rewards: Reward[];",
            "requirements: LevelRequirement[];", "costs: ItemCost[];");

        Separate();
        WriteUnion("export type DropTableName",
            _dropTables.Select(t => Quote(t.Name)).ToList());
        Separate();
        WriteUnion("export type ActivityName",
            _activities.Select(a => Quote(a.Name)).ToList());

        EmitDropTableData();
        EmitActivityData();
    }

    private void EmitDropTableData()
    {
        const string declaration =
            "export const DROP_TABLE_DATA: Record<DropTableName, DropTableDefinition> =";

        Separate();
        if (_dropTables.Count == 0)
        {
            _textWriter.WriteLine($"{declaration} {{}};");
            return;
        }

        using (Scope _ = _textWriter.Scope(declaration, ScopeStyle.Curly, ";"))
        {
            for (int i = 0; i < _dropTables.Count; i++)
            {
                DropTable table = _dropTables[i];
                string separator = i == _dropTables.Count - 1 ? "" : ",";
                using (Scope __ = _textWriter.Scope($"{table.Name}:", ScopeStyle.Curly, separator))
                {
                    WriteObjectArray("rewards: ",
                        Rewards(table.ItemRewards, table.TableRewards, table.XpRewards).Select(RewardMembers).ToList(),
                        "");
                }
            }
        }
    }

    private void EmitActivityData()
    {
        const string declaration =
            "export const ACTIVITY_DATA: Record<ActivityName, ActivityDefinition> =";

        Separate();
        if (_activities.Count == 0)
        {
            _textWriter.WriteLine($"{declaration} {{}};");
            return;
        }

        using (Scope _ = _textWriter.Scope(declaration, ScopeStyle.Curly, ";"))
        {
            for (int i = 0; i < _activities.Count; i++)
            {
                Activity activity = _activities[i];
                string separator = i == _activities.Count - 1 ? "" : ",";
                using (Scope __ = _textWriter.Scope($"{activity.Name}:", ScopeStyle.Curly, separator))
                {
                    _textWriter.WriteLine($"time: {activity.Time.ToString(CultureInfo.InvariantCulture)},");
                    WriteObjectArray("rewards: ",
                        Rewards(activity.ItemRewards, activity.TableReward, activity.XpRewards).Select(RewardMembers).ToList(),
                        ",");
                    WriteObjectArray("requirements: ",
                        activity.LevelRequirements.Select(RequirementMembers).ToList(), ",");
                    WriteObjectArray("costs: ",
                        activity.ItemCosts.Select(CostMembers).ToList(), "");
                }
            }
        }
    }

    private void WriteInterface(string name, params string[] members)
    {
        Separate();
        using (Scope _ = _textWriter.Scope($"export interface {name}"))
        {
            foreach (string member in members)
            {
                _textWriter.WriteLine(member);
            }
        }
    }

    private void WriteUnion(string declaration, IReadOnlyList<string> members)
    {
        if (members.Count == 0)
        {
            _textWriter.WriteLine($"{declaration} = never;");
            return;
        }

        string joined = string.Join(" | ", members);
        if (Fits($"{declaration} = {joined};"))
        {
            _textWriter.WriteLine($"{declaration} = {joined};");
            return;
        }

        _textWriter.WriteLine($"{declaration} =");
        using (Scope _ = new(ScopeStyle.Indentation, _textWriter))
        {
            if (Fits($"{joined};"))
            {
                _textWriter.WriteLine($"{joined};");
                return;
            }

            for (int i = 0; i < members.Count; i++)
            {
                string terminator = i == members.Count - 1 ? ";" : "";
                _textWriter.WriteLine($"| {members[i]}{terminator}");
            }
        }
    }

    private void WriteArray(string prefix, IReadOnlyList<string> elements, string suffix)
    {
        if (elements.Count == 0)
        {
            _textWriter.WriteLine($"{prefix}[]{suffix}");
            return;
        }

        string flat = $"{prefix}[{string.Join(", ", elements)}]{suffix}";
        if (Fits(flat))
        {
            _textWriter.WriteLine(flat);
            return;
        }

        _textWriter.WriteLine($"{prefix}[");
        using (Scope _ = new(ScopeStyle.Indentation, _textWriter))
        {
            for (int i = 0; i < elements.Count; i++)
            {
                string separator = i == elements.Count - 1 ? "" : ",";
                _textWriter.WriteLine($"{elements[i]}{separator}");
            }
        }
        _textWriter.WriteLine($"]{suffix}");
    }

    private void WriteObjectArray(string prefix, IReadOnlyList<IReadOnlyList<string>> elements,
        string suffix)
    {
        if (elements.Count == 0)
        {
            _textWriter.WriteLine($"{prefix}[]{suffix}");
            return;
        }

        List<string> flats = elements.Select(FlatObject).ToList();
        if (elements.Count == 1 && Fits($"{prefix}[{flats[0]}]{suffix}"))
        {
            _textWriter.WriteLine($"{prefix}[{flats[0]}]{suffix}");
            return;
        }

        _textWriter.WriteLine($"{prefix}[");
        using (Scope _ = new(ScopeStyle.Indentation, _textWriter))
        {
            for (int i = 0; i < elements.Count; i++)
            {
                string separator = i == elements.Count - 1 ? "" : ",";
                if (Fits(flats[i] + separator))
                {
                    _textWriter.WriteLine($"{flats[i]}{separator}");
                    continue;
                }

                using (Scope __ = _textWriter.Scope("", ScopeStyle.Curly, separator))
                {
                    for (int j = 0; j < elements[i].Count; j++)
                    {
                        string comma = j == elements[i].Count - 1 ? "" : ",";
                        _textWriter.WriteLine($"{elements[i][j]}{comma}");
                    }
                }
            }
        }
        _textWriter.WriteLine($"]{suffix}");
    }

    private static string FlatObject(IReadOnlyList<string> members)
    {
        return "{ " + string.Join(", ", members) + " }";
    }

    private bool Fits(string text)
    {
        return _textWriter.Indentations * TabWidth + text.Length <= PrintWidth;
    }

    private bool HasEnum(string name)
    {
        return _enums.Any(e => e.Name == name);
    }

    private static string[] RewardMembers(Reward reward)
    {
        return reward switch
        {
            ItemReward item => new[]
            {
                "kind: 'item'", $"count: {item.Count}", $"weight: {WeightLiteral(item.Weight)}",
                $"item: {Quote(item.Item)}",
            },
            TableReward table => new[]
            {
                "kind: 'table'", $"count: {table.Count}", $"weight: {WeightLiteral(table.Weight)}",
                $"table: {Quote(table.Table)}",
            },
            XpReward xp => new[]
            {
                "kind: 'xp'", $"count: {xp.Count}", $"weight: {WeightLiteral(xp.Weight)}",
                $"skill: {Quote(xp.Skill)}",
            },
            _ => throw new NotSupportedException("Reward expressions should drop a table, an item or xp."),
        };
    }

    private static string[] RequirementMembers(LevelRequirement requirement)
    {
        return new[] { $"skill: {Quote(requirement.Skill)}", $"count: {requirement.Count}" };
    }

    private static string[] CostMembers(ItemCost cost)
    {
        return new[] { $"item: {Quote(cost.Item)}", $"count: {cost.Cost}" };
    }

    private static string WeightLiteral(float? weight)
    {
        return weight is null ? "null" : weight.Value.ToString(CultureInfo.InvariantCulture);
    }

    private static string Quote(string value)
    {
        return $"'{value}'";
    }

    private static List<Reward> Rewards(
        List<ItemReward> items, List<TableReward> tables, List<XpReward> xps)
    {
        return items.Cast<Reward>().Concat(tables).Concat(xps).ToList();
    }
}
